spring:
  application:
    name: spring_security
  datasource:
    url: jdbc:mysql://${DB_LOCAL_HOST}/security_test?serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    password: ${DB_LOCAL_PASSWORD}
    username: ${DB_LOCAL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      connection-timeout: 30000
      maximum-pool-size: 30
      idle-timeout: 10
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.hibernate.default_batch_fetch_size: 100
    generate-ddl: true
    show-sql: true
  main:
    allow-bean-definition-overriding: true

server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true